agentuniverse/agent/plan/planner/peer_planner/peer_planner.py, agentuniverse/base/util/prompt_util.py, docs/guidebook/zh/1_3_快速开始.md
Fix: peer planner log format & prompt split texts issues
=> Fix: peer planner log format & prompt split texts issues

agentuniverse/agent/default/peer_agent.py, agentuniverse/agent/default/peer_agent.yaml, agentuniverse/base/agentuniverse.py
Feat: Add default peer agent to the agentUniverse.
=> Feat: Add default peer agent to the agentUniverse.

agentuniverse/agent/action/knowledge/embedding/openai_embedding.py, agentuniverse/llm/langchain_instance.py, sample_standard_app/app/core/knowledge/demo_knowledge.py
Improvement: modify the the initialization method of the openai llm and embedding model.
=> Improvement: modify the the initialization method of the openai llm and embedding model.

agentuniverse/prompt/prompt_model.py
[fix: prompt model bool function.](https://github.com/alipay/agentUniverse/commit/734cd9a0c2ef49ee9b439b697af1c20ed1496c60)
=> fix: prompt model bool function.

agentuniverse/llm/llm.py, agentuniverse/llm/openai_llm.py, sample_standard_app/app/core/agent/peer_agent_case/demo_expressing_agent.yaml, sample_standard_app/app/core/agent/peer_agent_case/demo_planning_agent.yaml, sample_standard_app/app/core/agent/rag_agent_case/demo_rag_agent.yaml, sample_standard_app/app/core/prompt/planning_agent_cn.yaml, tests/test_agentuniverse/unit/llm/test_llm.py
feat: add gpt-4o llm model in agentUniverse.
=> feat: add gpt-4o llm model in agentUniverse.

docs/guidebook/en/3_2_1_gRPC.md, docs/guidebook/zh/3_2_1_gRPC.md
=> Add: gRPC doc

agentuniverse/agent/agent.py, agentuniverse/agent/memory/message.py, agentuniverse/agent/plan/planner/planner.py, agentuniverse/agent/plan/planner/rag_planner/rag_planner.py, agentuniverse/base/util/prompt_util.py, agentuniverse/prompt/chat_prompt.py, agentuniverse/prompt/prompt.py, agentuniverse/prompt/prompt_model.py, sample_standard_app/app/core/agent/rag_agent_case/demo_multimodal_agent.yaml, sample_standard_app/app/test/test_multimodal_agent.py
1. [improvement: add message to langchain message functions in agentUniverse.]
2. [feat: add chat prompt template in agentUniverse.]
3. [feat: add image url to the rag planner (multimodal).]
4. [feat: add demo multimodal agent in agentUniverse.]
=> feat: add chat prompt template and image url to the rag planner (multimodal) in agentUniverse.

README.md, README_jp.md, README_zh.md
I created Japanese translated README.
=> docs: add Japanese README file

agentuniverse/agent/plan/planner/planner.py, docs/guidebook/en/6_2_1_Discussion_Group.md, docs/guidebook/zh/6_2_1_讨论组.md, sample_standard_app/app/core/agent/discussion_agent_case/host_agent.py, sample_standard_app/app/core/agent/discussion_agent_case/participant_agent.py, sample_standard_app/app/core/agent/peer_agent_case/demo_executing_agent.yaml, sample_standard_app/app/core/agent/peer_agent_case/demo_expressing_agent.yaml, sample_standard_app/app/core/agent/peer_agent_case/demo_planning_agent.yaml, sample_standard_app/app/core/agent/peer_agent_case/demo_reviewing_agent.yaml, sample_standard_app/app/core/memory/demo_memory.py, sample_standard_app/app/core/planner/discussion_planner.py, sample_standard_app/app/core/prompt/host_agent_cn.yaml, sample_standard_app/app/core/prompt/host_agent_en.yaml, sample_standard_app/app/core/prompt/participant_agent_cn.yaml, sample_standard_app/app/core/prompt/participant_agent_en.yaml
feat: add demo discussion agents in agentUniverse.
=> feat: add demo discussion agents in agentUniverse.

agentuniverse/base/util/prompt_util.py
Improvement: tweak comments in the prompt_util file
=> Improvement: tweak comments in the prompt_util file

docs/guidebook/en/5_1_1_Docker_Container_Deployment.md, docs/guidebook/en/5_1_2_K8S_Deployment.md, docs/guidebook/zh/5_1_1_Docker容器化部署.md, docs/guidebook/zh/5_1_2_K8S部署.md
Add: docker image site in documents
Change: The path you mount into the container while using local dir in docker deployment.
=> Add: docker image site in documents. Change: The path mount into the container 

agentuniverse/agent/agent.py, agentuniverse/agent/default/executing_agent/executing_agent.py, agentuniverse/base/annotation/trace.py, agentuniverse/base/util/monitor/monitor.py, docs/guidebook/en/2_5_1_Monitor_Module.md, docs/guidebook/zh/2_5_1_监控模块.md, sample_standard_app/app/test/test_rag_agent.py
feat: add trace_agent annotation to trace the agent invocation record.
=> feat: add trace_agent annotation to trace the agent invocation record.

agentuniverse/agent_serve/web/dal/request_library.py, agentuniverse/database/sqldb_wrapper.py
Fix: Multi session conflict in async service run
=> Fix: Multi session conflict in async service run

docs/guidebook/en/2_2_3_Integrated_Tools.md, docs/guidebook/zh/2_2_3_集成的工具.md
fix the get request doc in en and zh
=> fix: integrated_tool doc fix

agentuniverse_product/agentuniverse_product.py
support setting magent_ui with configuration file
```toml
[MAGENT_UI]
port=8888
host='0.0.0.0'
root_path = '/root'
```
=> feature: support setting magent_ui with configuration file

agentuniverse/agent_serve/web/dal/request_library.py
FIX: Auto system sqlite db path error on windows
=> FIX: Auto system sqlite db path error on windows

agentuniverse/agent/action/knowledge/reader/file/txt_reader.py
FIX: txt reader not implement bug
=> FIX: txt reader not implement bug

agentuniverse_product/base/product.py, agentuniverse_product/service/agent_service/agent_service.py, agentuniverse_product/service/model/agent_dto.py
=> feat: add the latest modify time api to the product

agentuniverse/agent/action/knowledge/store/milvus_store.py
FIX: Some versions of Milvus do not support returning vector results.
=> FIX: Some versions of Milvus do not support returning vector results.

agentuniverse/agent/action/knowledge/knowledge.py, agentuniverse/agent_serve/web/flask_server.py, agentuniverse/agent_serve/web/thread_with_result.py
=> Fix: Merge Bug

docs/guidebook/en/Concepts/Cerebrum_Agent.md, docs/guidebook/zh/设计理念/主脑智能体.md, examples/sample_apps/cerebrum_agent_app/intelligence/agentic/agent/agent_instance/cerebrum_agent_case/simple_cerebrum_agent.yaml, examples/sample_apps/cerebrum_agent_app/intelligence/agentic/agent/agent_template/simple_cerebrum_agent_template.py, examples/sample_apps/cerebrum_agent_app/intelligence/test/run_cerebrum_agent.py
Change: Make cerebrum agent example more flexible
=> Change: Make cerebrum agent example more flexible

agentuniverse/agent/action/knowledge/reader/file/website_bs4_reader.py, agentuniverse/agent/action/knowledge/reader/file/website_bs4_reader.yaml
**function**
add website reader based on BeautifulSoup
**Usage**
readers:
url: default_website_bs4_reader
=> add website bs4 reader

.github/ISSUE_TEMPLATE/issue_template-bug.md
**When submitting a PR, please confirm the following points and put ☑️ in the boxes one by one:** | **在提出pr时，请确认了以下几点，并逐一确认勾选：** 
**Checklist:**
-
-
-
-
-
=> chore: update issue_template-bug.md

agentuniverse/agent/action/tool/common_tool/add_simple_tool.yaml, agentuniverse/agent/action/tool/common_tool/bing_search_tool.yaml, agentuniverse/agent/action/tool/common_tool/div_simple_tool.yaml, agentuniverse/agent/action/tool/common_tool/duckduckgo_search.yaml, agentuniverse/agent/action/tool/common_tool/google_search_tool.yaml, agentuniverse/agent/action/tool/common_tool/human_input_run.yaml, agentuniverse/agent/action/tool/common_tool/info_sql_database_tool.yaml, agentuniverse/agent/action/tool/common_tool/list_sql_database_tool.yaml, agentuniverse/agent/action/tool/common_tool/mul_simple_tool.yaml, agentuniverse/agent/action/tool/common_tool/python_repl_tool.yaml, agentuniverse/agent/action/tool/common_tool/query_sql_database_tool.yaml, agentuniverse/agent/action/tool/common_tool/request_get_tool.yaml, agentuniverse/agent/action/tool/common_tool/request_post_tool.yaml, agentuniverse/agent/action/tool/common_tool/search_api_baidu_tool.yaml, agentuniverse/agent/action/tool/common_tool/search_api_bing_tool.yaml, agentuniverse/agent/action/tool/common_tool/sub_simple_tool.yaml, agentuniverse/agent/action/tool/common_tool/wikipedia_query.yaml
=> add default config

agentuniverse/llm/default/claude_llm.py, agentuniverse/llm/default/deep_seek_openai_style_llm.py
=> fix deepseek

agentuniverse/agent/action/knowledge/embedding/doubao_embedding.py, agentuniverse/agent/action/knowledge/embedding/doubao_embedding.yaml, tests/test_agentuniverse/unit/agent/action/knowledge/embedding/test_doubao_embedding.py
feat: Add Doubao Embedding Integration for Text Embedding
Added a new Doubao Embedding component that integrates with Volcengine's Ark Runtime API to provide text embedding capabilities. This embedding component supports multiple dimension options and includes L2 normalization, enhancing the system's vector representation capabilities.
1. Doubao Embedding Implementation ([doubao_embedding.py](cci:7://file:///e:/agentUniverse/agentuniverse/agent/action/knowledge/embedding/doubao_embedding.py:0:0-0:0)):
- Integration with Volcengine Ark Runtime API
- Support for multiple embedding dimensions (512, 1024, 2048)
- L2 normalization for embedding vectors
- Lazy loading of dependencies
- Environment variable based configuration
- Dimension slicing support
2. Test Implementation …
=> feat: add doubao embedding. resolves #251

agentuniverse/agent/template/react_agent_template.py, docs/guidebook/en/Get_Start/2.Run_Your_First_Tutorial_Example.md, docs/guidebook/zh/开始使用/2.运行第一个教程案例.md
- 添加react agent 调试 gemini 的过程视频 resolves #256 
- 修复react agent 填充 tool_name 的bug
- fix tool_name
-
=> add gemini example video resolves #256 , fix react agent tool_name build

examples/sample_standard_app/intelligence/agentic/tool/samples/jina_ai_tool.py, examples/sample_standard_app/intelligence/agentic/tool/samples/jina_ai_tool.yaml, examples/sample_standard_app/intelligence/test/test_jina_ai_tool.py
#252 
-  [✅] I have read and understood the [contributor guidelines](https://github.com/antgroup/agentUniverse/blob/master/CONTRIBUTING.md). | 我已阅读并理解[贡献者指南](https://github.com/antgroup/agentUniverse/blob/master/CONTRIBUTING_zh.md) 。
- [✅] I have checked for any duplicate features related to this request and communicated with the project maintainers. | 我已检查没有与此请求重复的功能并与项目维护者进行了沟通。
- [✅] I accept the suggestion of the maintainers to make changes to or close this PR. | 我接受此PR配合维护人员的建议进行修改或关闭。
- [ ✅] I have submitted the test files and can provide screenshots of the test results (required for feature or bug fixes) | …
=> add jina.ai tool support webpage read, search, check fact. #252 

agentuniverse/llm/default/wenxin_llm.py, agentuniverse/llm/wenxin_langchain_instance.py, examples/sample_standard_app/config/yaml_func_extension.py, examples/sample_standard_app/intelligence/agentic/llm/ernie_3_5_128k.yaml, examples/sample_standard_app/intelligence/agentic/llm/ernie_3_5_8k.yaml, examples/sample_standard_app/intelligence/agentic/llm/ernie_3_5_8k_preview.yaml, examples/sample_standard_app/intelligence/agentic/llm/ernie_4_8k.yaml, examples/sample_standard_app/intelligence/agentic/llm/ernie_4_8k_latest.yaml, examples/sample_standard_app/intelligence/agentic/llm/ernie_4_8k_preview.yaml, examples/sample_standard_app/intelligence/agentic/llm/ernie_4_turbo_128k.yaml, examples/sample_standard_app/intelligence/agentic/llm/ernie_4_turbo_8k.yaml, examples/sample_standard_app/intelligence/agentic/llm/ernie_4_turbo_8k_latest.yaml, examples/sample_standard_app/intelligence/agentic/llm/ernie_4_turbo_8k_preview.yaml
=> chore: update wenxin LLM attributes

agentuniverse/agent/action/knowledge/rag_router/nlu_rag_router.py, agentuniverse/agent/default/rag_agent/memory_summarize_agent.yaml, agentuniverse/base/agentuniverse.py, agentuniverse/base/config/application_configer/app_configer.py, agentuniverse/llm/default/default_ollama_llm.py, agentuniverse/llm/default/qwen_openai_style_llm.yaml, agentuniverse/llm/default/wenxin_llm.py
=> fix: regression test bug fixes before new release

agentuniverse/base/agentuniverse.py, agentuniverse/base/annotation/trace.py, agentuniverse/base/component/component_manager_base.py, agentuniverse/base/util/monitor/monitor.py, examples/sample_standard_app/config/yaml_func_extension.py
=> fix: Resolve duplicate registrations.

agentuniverse/base/util/system_util.py
=> fix: standardize path format across Windows and Linux

examples/sample_standard_app/intelligence/agentic/tool/jina_ai_tool.yaml
- The issue was resolved due to unclear descriptions in the `description` field of the YAML, which caused the model to fail to pass parameters correctly under the React mode.
- examples\sample_standard_app\intelligence\agentic\tool\jina_ai_tool.yaml
- jina_ai_tool.yaml
=> fix jina-tool yaml

pyproject.toml
- https://github.com/agentuniverse-ai/agentUniverse/blob/master/agentuniverse/base/config/configer.py#L11 中 `import tomli`  未在依赖文件中体现，导致运行报错
-
-
-
-
=> fix: add missed dependency `tomli`

agentuniverse/base/component/component_manager_base.py
=> chore: Correct comments.

agentuniverse/agent/action/tool/common_tool/view_file_tool.py, tests/test_agentuniverse/unit/agent/action/tool/test_view_file.py
Implemented a file viewing tool for the AgentUniverse framework. This enhancement enables agents to read file contents with precise control over line ranges, providing essential capabilities for code analysis, configuration management, and data processing. The implementation supports viewing entire files or specific sections with comprehensive metadata.
- File content retrieval with line range specification
- Boundary validation to prevent out-of-range access
- Comprehensive file metadata in response
- Unit tests for viewing entire files
- Unit tests for viewing specific line ranges
- Error handling verification for invalid file paths
- Line number boundary validation testing
- <img width="650" alt="image" src="https://github.com/user-attachments/assets/72f48253-c66a-460e-a266-989a9b8bb085 …
=> feat: add view file tool. resolves #252

agentuniverse/agent/action/tool/common_tool/write_file_tool.py, tests/test_agentuniverse/unit/agent/action/tool/test_write_file.py
Implemented a file writing tool for the AgentUniverse framework. This enhancement enables agents to create new files and modify existing ones, providing essential capabilities for code generation, configuration management, and data persistence. The implementation supports both creating new files and appending to existing files with automatic directory creation.
- New file creation with automatic directory structure creation
- Append mode for extending existing files
- Operation metadata including bytes written and file size
- Robust error handling for permission issues and invalid paths
- Unit tests for creating new files
- Unit tests for appending to existing files
- Unit tests for automatic directory structure creation
- <img width="650" alt="image" …
=> feat: add write file tool. resolves #252

agentuniverse/agent/action/tool/common_tool/tavily_tool.py, examples/sample_standard_app/intelligence/agentic/tool/tavily_tool.yaml, examples/sample_standard_app/intelligence/test/test_tavily_tool.py
#252 
-add tavily tool support webpage read, search, check fact.
-add test demo for tavily tool.
-examples/sample_standard_app/intelligence/test/test_tavily_tool.py
-agentuniverse/agent/action/tool/common_tool/tavily_tool.py
-examples/sample_standard_app/intelligence/agentic/tool/tavily_tool …
=> add tavily tool support search and extract information from website. #252 

agentuniverse/agent/action/knowledge/doc_processor/character_text_splitter.py, agentuniverse/agent/action/knowledge/doc_processor/dashscope_reranker.py, agentuniverse/agent/action/knowledge/doc_processor/doc_processor.py, agentuniverse/agent/action/knowledge/doc_processor/hierarchical_regex_text_spliter.py, agentuniverse/agent/action/knowledge/doc_processor/jieba_keyword_extractor.py, agentuniverse/agent/action/knowledge/doc_processor/recursive_character_text_splitter.py, agentuniverse/agent/action/knowledge/doc_processor/token_text_splitter.py
- the method comments in the agentuniverse/agent/action/knowledge/doc_processor  
-
-
-
- the method comments in the agentuniverse/agent/action/knowledge/doc_processor
=> chore:update doc_processor comment

docs/guidebook/en/In-Depth_Guides/Components/LLMs/BaiChuan_LLM_Use.md, docs/guidebook/en/In-Depth_Guides/Components/LLMs/Claude_LLM_Use.md, docs/guidebook/en/In-Depth_Guides/Components/LLMs/DeepSeek_LLM_Use.md, docs/guidebook/en/In-Depth_Guides/Components/LLMs/GLM_LLM_Use.md, docs/guidebook/en/In-Depth_Guides/Components/LLMs/Kimi_LLM_Use.md, docs/guidebook/en/In-Depth_Guides/Components/LLMs/OpenAI_LLM_Use.md, docs/guidebook/en/In-Depth_Guides/Components/LLMs/Qwen_LLM_Use.md, docs/guidebook/en/In-Depth_Guides/Components/LLMs/WenXin_LLM_Use.md, docs/guidebook/en/In-Depth_Guides/Tutorials/LLM/LLM_component_define_and_usage.md, docs/guidebook/zh/In-Depth_Guides/原理介绍/模型/模型定义与使用.md, docs/guidebook/zh/In-Depth_Guides/组件列表/模型列表/BaiChuan使用.md, docs/guidebook/zh/In-Depth_Guides/组件列表/模型列表/Claude使用.md, docs/guidebook/zh/In-Depth_Guides/组件列表/模型列表/DeepSeek使用.md, docs/guidebook/zh/In-Depth_Guides/组件列表/模型列表/Kimi使用.md, docs/guidebook/zh/In-Depth_Guides/组件列表/模型列表/OpenAI使用.md, docs/guidebook/zh/In-Depth_Guides/组件列表/模型列表/Qwen使用.md, docs/guidebook/zh/In-Depth_Guides/组件列表/模型列表/文心使用.md, docs/guidebook/zh/In-Depth_Guides/组件列表/模型列表/智谱GLM使用.md
…erse sample standard app.
-
-
-
-
-
=> docs: enrich LLM documentation and align configuration with aU sample standard app

agentuniverse/agent/action/knowledge/reader/cloud_file_reader/feishu_reader.py, agentuniverse/agent/action/knowledge/reader/cloud_file_reader/feishu_reader.yaml
-
-增加了reader的公开飞书云文档的阅读功能
-
-
agentUniverse/agentuniverse/agent/action/knowledge/reader/cloud_file_reader/feishu_reader.py
-
agentUniverse/agentuniverse/agent/action/knowledge/reader/cloud_file_reader/feishu_reader.py
agentUniverse/agentuniverse/agent/action/knowledge/reader/cloud_file_reade …
=> feat: The ability for Reader to read publicly accessible Feishu cloud documents has been added.

agentuniverse/agent/action/knowledge/reader/cloud_file_reader/feishu_reader.py
-
-修改了feishu_reader.py中的部分内容，使其更加规范
-
-同上次修改，不改变输出
-feishu_reader.py
=> refactor：reconstruct some code in feishu_reader.py

CHANGELOG.md, CHANGELOG_zh.md, README.md, README_jp.md, README_zh.md
=> feat: Release version 0.0.16

agentuniverse/llm/llm_channel/langchain_instance/default_channel_langchain_instance.py, agentuniverse/llm/llm_channel/llm_channel.py
=> 修复channel问题

docs/guidebook/en/How-to/Guide to Connecting agentUniverse via Chatbox/Guide to Connecting agentUniverse via Chatbox.md
=> 新增openai工具英文说明文档

agentuniverse/agent/action/knowledge/reader/cloud_file_reader/yuque_reader.py, agentuniverse/agent/action/knowledge/reader/cloud_file_reader/yuque_reader.yaml
- Add yuque document cloud knowledge reader.
-
-
-
-
=> feat: Add yuque document knowledge reader

agentuniverse/agent_serve/web/mcp/mcp_server_manager.py, pyproject.toml
=> FIX: match mcp 1.9.0

agentuniverse/agent/agent.py, agentuniverse/base/util/tracing/au_trace_manager.py
=> 修复scene_code问题

agentuniverse/agent/agent.py
FIX: Add warning while failed invoke tool
=> FIX: Add warning while failed invoke tool

agentuniverse/agent_serve/web/mcp/mcp_server_manager.py, docs/guidebook/zh/In-Depth_Guides/技术组件/服务化/MCP_Server.md
CHANGE: as_mcp_tool only accept bool and dict
=> CHANGE: as_mcp_tool only accept bool and dict

agentuniverse/base/util/tracing/au_trace_manager.py, agentuniverse/llm/llm_channel/llm_channel.py, agentuniverse/llm/openai_style_llm.py
=> 兼容用户传递的extra_body

examples/sample_apps/peer_agent_app/config/config.toml
- when adding custom search tool in peer_agent_app, I got the below error:
"TypeError: the 'package' argument is required to perform a relative import for '.intelligence.agentic.tool.kuake_search_tool'"
the below is package structure
This PR is to add ROOT_PACKAGE parameter to fix the tool loading issue
- Please ignore this PR if the error is caused by my misunderstanding
-
- test files listed here: …
=> fixed peer_agent_app startup failure when adding customized tool

agentuniverse/llm/llm_channel/llm_channel.py
fix llm channel init extra params bug
=> fix llm channel init extra params bug

agentuniverse/base/tracing/otel/instrumentation/llm/llm_instrumentor.py, agentuniverse/llm/openai_style_llm.py
Fix: Lose Token otel trace when not use llm channel
=> Fix: Lose Token otel trace when not use llm channel

agentuniverse/agent/agent.py, agentuniverse/agent/agent_model.py, agentuniverse/agent/default/rag_route_agent/nlu_rag_route_agent.py, agentuniverse/agent/template/agent_template.py, agentuniverse/agent/template/executing_agent_template.py, agentuniverse/agent/template/expressing_agent_template.py, agentuniverse/agent/template/nl2api_agent_template.py, agentuniverse/agent/template/peer_agent_template.py, agentuniverse/agent/template/planning_agent_template.py, agentuniverse/agent/template/rag_agent_template.py, agentuniverse/agent/template/react_agent_template.py, agentuniverse/agent/template/reviewing_agent_template.py, agentuniverse/agent_serve/web/after_register_queue.py, agentuniverse/agent_serve/web/dal/request_library.py, agentuniverse/agent_serve/web/flask_server.py, agentuniverse/base/agentuniverse.py
Feature: agent model read property through property loader
=> Feature: agent model read property through property loader

agentuniverse/base/context/context_archive_utils.py, agentuniverse/base/context/context_coordinator.py, agentuniverse/base/context/mcp_session_manager.py, examples/sample_standard_app/intelligence/agentic/agent/agent_instance/demo_agent.py
- [√] I have read and understood the [contributor guidelines](https://github.com/antgroup/agentUniverse/blob/master/CONTRIBUTING.md). | 我已阅读并理解[贡献者指南](https://github.com/antgroup/agentUniverse/blob/master/CONTRIBUTING_zh.md) 。
- [√] I have checked for any duplicate features related to this request and communicated with the project maintainers. | 我已检查没有与此请求重复的功能并与项目维护者进行了沟通。
- [√] I accept the suggestion of the maintainers to make changes to or close this PR. | 我接受此PR配合维护人员的建议进行修改或关闭。
- [ √] I have added or modified the documentation related to this PR | 我已经添加或修改了本次pr对应的文档说明(非必要，根据实际PR内容按需添加)
**Please fill in the specific details of …
=> docs: add Google-style docstrings for context modules and demo_agent

EXCEL_SUPPORT_UPDATE.md, agentuniverse/agent/action/knowledge/reader/file/__init__.py, agentuniverse/agent/action/knowledge/reader/file/file_reader.py, agentuniverse/agent/action/knowledge/reader/file/xlsx_reader.py, agentuniverse/agent/action/knowledge/reader/file/xlsx_reader.yaml, examples/sample_apps/excel_reader_demo.py, tests/test_agentuniverse/unit/agent/action/knowledge/reader/file/test_xlsx_reader.py
- [ x] I have submitted the test files and can provide screenshots of the test results (required for feature or bug fixes) | 我已经提交了测试文件并可提供测试结果截图(功能修改、BUG修复类PR必须提供，其他按需)
- [ x] I have added or modified the documentation related to this PR | 我已经添加或修改了本次pr对应的文档说明(非必要，根据实际PR内容按需添加)
- [x ] I have added examples and notes if needed | 我已经添加了使用案例代码与文档说明(非必要，根据实际PR内容按需添加)
为AgentUniverse框架添加了完整的Excel文件读取支持，完善Office文档处理能力。现在框架可以处理Word、Excel、PowerPoint等主流办公文档格式。
- 新增XlsxReader类支持Excel文件读取
- 集成到FileReader自动文件类型识别  
- 支持多工作表处理和丰富元数据
- 添加完整的单元测试覆盖
- 提供演示示例和详细文档
- …
=>    feat: 添加Excel文件读取支持 (.xlsx)
